name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 24.x

      - name: install
        run: npm i

      - name: build
        run: npm run build

      - name: test
        run: npm run coverage

      - name: report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
